replicaCount: 1

image:
  repository: davidvoodo/simple-flask-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
