name: Matrix Build
on:
  push:
    branches:
        - test
  workflow_dispatch:
     

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MYVAR: "Hello, World!"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: show var
        run: |
          echo ${{ env.MYVAR }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
