name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  quick-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements-dev.txt

      - name: Quick lint check
        run: |
          cd app
          python -m pylint app.py --fail-under=7.0

      - name: Quick test run
        run: |
          cd app
          python -m pytest ../tests/ -v

      - name: Helm chart validation
        run: |
          helm lint ./mychart

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
